name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Add your Vercel token in GitHub Secrets
          vercel-args: "--prod=false" # Ensure it deploys to a preview environment
          working-directory: . # Update if your API is in a subdirectory
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Capture the deployment URL
      - name: Set Preview URL
        run: echo "PREVIEW_URL=${{ steps.vercel-deploy.outputs.preview_url }}" >> $GITHUB_ENV

      # Smoke tests
      - name: Run Smoke Tests
        run: npm run smoke-test
        env:
          API_URL: ${{ env.PREVIEW_URL }}
