name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci

      # Deploy to Vercel (only on push to main)
      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod=false'
          working-directory: .
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Debug step to see the URL
      - name: Debug Preview URL
        run: |
          echo "Preview URL from Vercel: ${{ steps.vercel-deploy.outputs.preview-url }}"
          echo "Current API_URL: ${{ env.API_URL }}"

      # Set Preview URL with https if needed
      - name: Set Preview URL
        run: |
          PREVIEW_URL="${{ steps.vercel-deploy.outputs.preview-url }}"
          if [[ ! $PREVIEW_URL =~ ^https:// ]]; then
            PREVIEW_URL="https://$PREVIEW_URL"
          fi
          echo "API_URL=$PREVIEW_URL" >> $GITHUB_ENV

      # Smoke tests with explicit environment variable
      - name: Run Smoke Tests
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}  # Add this line
          API_URL: ${{ env.API_URL }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NODE_ENV: test
        run: |
          echo "Running tests with API_URL: $API_URL"
          echo "Vercel token is: $VERCEL_TOKEN"
          npm run test:smoke
